[package]
name = "recovery"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
probe-rs = "0.29.1"
thiserror = "2.0.12"
